### ISSUE TITLE
Add maximum output file size, split output if it surpasses this limit.

### ISSUE THREAD

**Issue by kbirk** [unchartedsoftware/census-hackathon-2016#2]
Currently the ditribution of data across the files is not uniforn. One file accounts for more than 70% of the data. 

We should introduce a const, such as 100MB or N records, which will split output.

Ex. xfyi-uyt5.csv will be split into xfyi-uyt5_0.csv, xfyi-uyt5_1.csv, ... etc.

**Comment by Ghnuberath** [comment]
Fixed by ae2ddfd510cde3b65dd2ee10db3298d7a65f469d
